### PR TITLE
[Bugfix] Explicit time integration error

### PR DESCRIPTION
**Pull request by bodhinandach**
**Describe the PR**
This PR fix issue https://github.com/geomechanics/mpm/issues/36. Basically, it uses the half-time step velocity as a remedy.

**Related Issues/PRs**
Issue https://github.com/geomechanics/mpm/issues/36

**Additional context**
N/A

### CODE REVIEW

**Review by jgiven100 — APPROVED** [review]
Quickly implemented and verified updated formulation for single MP falling. Good fix :+1:

**Review by yliang-sn — APPROVED** [review]

**Comment by migmolper** [comment]
Looks good, good catch !

**Review by migmolper — APPROVED** [review]
Looks good

**Review by RyotaHashimoto — APPROVED** [review]
Looks good. Thank you.

**Pull request merged**
