### PR TITLE
[NorSand] Fix sign error and add crit state cap option

### PR DESCRIPTION
**Pull request by jgiven100**
**Describe the PR**

Fix sign error for `dtheta_dsigma`. 

* Formulation for `dtheta_dsigma` is sign independent, so passing the current stress state as either compression *or* tension positive returns the same result!
* Material utility is based on tension positive. 
* Need `-1.` factor since NorSand is based on compression positive. 

Add option for forcing image critical stress ratio -> critical stress ratio.

* Not default behavior
* "Max cap" for state parameter (currently 0.5)
* Range of pdstrain to bring down the reduction factor (currently 0.5 -> 1.0)

**Related Issues/PRs**
N/a

**Additional context**
N/a

### CODE REVIEW

**Comment by jgiven100** [comment]
ADD:
```
if (bolton_csl_) {
   emax - emin
   ...
}
```

**Comment by bodhinandach** [comment]
I tried the modification in implicit MPM, but unfortunately, it cannot run successfully with a larger time step. This is, perhaps, because of the fact that we are not using a return mapping algorithm in the NorSand formulation.

**Comment by bodhinandach** [comment]
Also, I tried to output the residuals of the implicit solver, and it seems that one of the conditions might cause `NaN` in stresses. Any clue @jgiven100?

**Comment by bodhinandach** [comment]
@jgiven100 Let's have a look at this again. Do you want to make further repairs according to what you have investigated over the past week? Otherwise, I am happy to approve. We might not be able to run implicit with the current NorSand. So let's go with this for now.

**Review by bodhinandach — APPROVED** [review]

**Pull request merged**
