### PR TITLE
[Cleanup] Remove unused variables

### PR DESCRIPTION
**Pull request by bodhinandach**
**Describe the PR**
This PR removes some unused variables majorly from the tests. It also adds some missing exception caught throw.

**Related Issues/PRs**
N/A

**Additional context**
N/A

### CODE REVIEW

**Comment by jgiven100** [comment]
@bodhinandach thanks for the effort on this - I'll take a look after testing passes!

**Review by jgiven100 — COMMENTED** [review]
Looks like we don't "force" a console error for 3 of the tests where you added to the existing catch statement. Likewise, doesn't looke like the clock time is actually being output anywhere. Do we want to cover these?

**Comment by bodhinandach** [comment]
The performance benchmarks are actually called, but I am not sure why it is marked as "not checked". I will try to see if I can implement the catch statements.

**Comment by bodhinandach** [comment]
@jgiven100 I found out the catch in GIMP element is not necessary. Other than that, I think there are several other things that can be optimized in our elements, which will improve the efficiency and also improve the coverages. However, I think it's better to perform cleanup at once after PR https://github.com/geomechanics/mpm/pull/27 and https://github.com/geomechanics/mpm/pull/49 are merged. I will put that on my to-do list over the summer.

**Review by jgiven100 — APPROVED** [review]

**Pull request merged**
